config:
  count: 20000000  #跑多少次
  assignline: [0,0] #指定中奖项
  outfile: "out.txt"  #指定输出文件名
  debug: false  #true/false
  freeassignline: [1,10] #指定free中奖项
  hitscatter: 3 #指定几个scatter进free
  hitbonus: 6 #指定几个bonus中respin
  respincount: 3 #指定几次respin