package count

import (
	"chao/lun"
	"encoding/json"
	"fmt"
)

func Score(ag *lun.AutoGenerated, winnumber map[int]int) int {
	////////////////通过json序列化把结构体转化成map
	b, err := json.Marshal(ag.ScoreCfg)
	if err != nil {
		fmt.Println(err)
	}
	scorecfg := make(map[int][]int, 10)
	err = json.Unmarshal(b, &scorecfg)
	if err != nil {
		fmt.Println(err)
	}
	//m := structs.Map(&a)
	//fmt.Println(m)
	////////////////////////****************
	var scoremax int
	scoremax = 0
	//var scorenumber int
	var scoretmp int
	scoretmp = 0
	for k, v := range winnumber {
		for i, j := range scorecfg {
			if k == i {
				scoretmp = j[v-1]
				if scoretmp >= scoremax {
					scoremax = scoretmp
					//scorenumber = i
				}
				//fmt.Printf("winnum:%v,score:%v\n", i, j[v-1])
			}
		}
	}
	//fmt.Printf("scorenumber:%v,scoremax:%v\n", scorenumber, scoremax)
	return scoremax
}
